"""Tests for llm_forge.model_card module.

Tests generate_model_card() with various field combinations,
required sections, custom extra_sections, and minimal inputs.
"""

import pytest

from llm_forge.model_card import generate_model_card


class TestGenerateModelCardAllFields:
    """Tests for generate_model_card() with all fields provided."""

    def test_header_contains_model_name(self) -> None:
        """Card header includes the model name."""
        card = generate_model_card(name="my-model")
        assert "# Model Card: my-model" in card

    def test_contains_generated_timestamp(self) -> None:
        """Card contains a generated-on timestamp."""
        card = generate_model_card(name="m")
        assert "Generated on" in card

    def test_overview_contains_base_model(self) -> None:
        """Overview table includes base model when provided."""
        card = generate_model_card(name="m", base_model="llama-3-8b")
        assert "llama-3-8b" in card

    def test_overview_contains_task(self) -> None:
        """Overview table includes task in uppercase."""
        card = generate_model_card(name="m", task="dpo")
        assert "DPO" in card

    def test_training_config_section(self) -> None:
        """Training Configuration section is rendered with config params."""
        card = generate_model_card(
            name="m",
            config={"lr": 2e-5, "epochs": 3, "batch_size": 4},
        )
        assert "## Training Configuration" in card
        assert "lr" in card
        assert "epochs" in card
        assert "batch_size" in card

    def test_dataset_section(self) -> None:
        """Training Data section shows dataset info."""
        card = generate_model_card(
            name="m",
            dataset_info={"name": "my_dataset", "rows": 10000},
        )
        assert "## Training Data" in card
        assert "my_dataset" in card

    def test_metrics_section(self) -> None:
        """Evaluation Metrics section shows metric values."""
        card = generate_model_card(
            name="m",
            metrics={"accuracy": 0.95, "f1": 0.92},
        )
        assert "## Evaluation Metrics" in card
        assert "accuracy" in card
        assert "0.9500" in card

    def test_environment_section(self) -> None:
        """Training Environment section shows environment info."""
        card = generate_model_card(
            name="m",
            environment={"gpu": "A100", "framework": "pytorch"},
        )
        assert "## Training Environment" in card
        assert "A100" in card

    def test_environment_packages_excluded(self) -> None:
        """'packages' key in environment is excluded from output."""
        card = generate_model_card(
            name="m",
            environment={"gpu": "A100", "packages": ["torch", "transformers"]},
        )
        assert "packages" not in card.split("## Training Environment")[1].split("##")[0]

    def test_intended_use_custom(self) -> None:
        """Custom intended_use text appears in card."""
        card = generate_model_card(name="m", intended_use="For research only.")
        assert "For research only." in card

    def test_limitations_custom(self) -> None:
        """Custom limitations text appears in card."""
        card = generate_model_card(name="m", limitations="Not for production.")
        assert "Not for production." in card

    def test_extra_sections_appended(self) -> None:
        """Custom extra_sections are appended with correct titles."""
        card = generate_model_card(
            name="m",
            extra_sections={
                "Ethical Considerations": "Be careful with bias.",
                "Deployment Notes": "Use behind an API gateway.",
            },
        )
        assert "## Ethical Considerations" in card
        assert "Be careful with bias." in card
        assert "## Deployment Notes" in card

    def test_footer_present(self) -> None:
        """Footer with 'Generated by LLM Forge' is present."""
        card = generate_model_card(name="m")
        assert "Generated by LLM Forge" in card


class TestGenerateModelCardMinimal:
    """Tests for generate_model_card() with minimal fields."""

    def test_minimal_card_contains_required_sections(self) -> None:
        """Minimal card has all required sections."""
        card = generate_model_card(name="minimal-model")
        assert "## Overview" in card
        assert "## Intended Use" in card
        assert "## Limitations" in card

    def test_minimal_card_default_intended_use(self) -> None:
        """Minimal card uses default intended use text."""
        card = generate_model_card(name="m")
        assert "intended for use in controlled environments" in card

    def test_minimal_card_default_limitations(self) -> None:
        """Minimal card uses default limitations text."""
        card = generate_model_card(name="m")
        assert "May reproduce biases" in card

    def test_no_training_config_section_when_empty(self) -> None:
        """Training Configuration section absent when config is empty."""
        card = generate_model_card(name="m", config={})
        assert "## Training Configuration" not in card

    def test_no_dataset_section_when_empty(self) -> None:
        """Training Data section absent when dataset_info is empty."""
        card = generate_model_card(name="m", dataset_info={})
        assert "## Training Data" not in card

    def test_no_metrics_section_when_empty(self) -> None:
        """Evaluation Metrics section absent when metrics is empty."""
        card = generate_model_card(name="m", metrics={})
        assert "## Evaluation Metrics" not in card

    def test_no_environment_section_when_empty(self) -> None:
        """Training Environment section absent when environment is empty."""
        card = generate_model_card(name="m", environment={})
        assert "## Training Environment" not in card


class TestGenerateModelCardFormat:
    """Tests for output format correctness."""

    def test_output_is_string(self) -> None:
        """Output is a string."""
        card = generate_model_card(name="m")
        assert isinstance(card, str)

    def test_lora_rank_in_overview(self) -> None:
        """LoRA rank appears in overview when in config."""
        card = generate_model_card(name="m", config={"lora_r": 16})
        assert "LoRA Rank" in card
        assert "16" in card

    def test_quantization_in_overview(self) -> None:
        """Quantization appears in overview when in config."""
        card = generate_model_card(name="m", config={"quantization": "4bit"})
        assert "Quantization" in card
        assert "4bit" in card

    def test_dataset_private_keys_excluded(self) -> None:
        """Dataset keys starting with '_' are excluded."""
        card = generate_model_card(
            name="m",
            dataset_info={"name": "ds", "_internal": "secret"},
        )
        assert "_internal" not in card
        assert "secret" not in card

    def test_float_metrics_formatted(self) -> None:
        """Float metrics are formatted to 4 decimal places."""
        card = generate_model_card(name="m", metrics={"loss": 0.123456789})
        assert "0.1235" in card

    def test_non_float_metrics_shown_as_is(self) -> None:
        """Non-float metrics are shown without formatting."""
        card = generate_model_card(name="m", metrics={"status": "complete"})
        assert "complete" in card
